export const CATALOGUE_LIST_REQUEST = 'CATALOGUE_LIST_REQUEST'
export const CATALOGUE_LIST_SUCCESS = 'CATALOGUE_LIST_SUCCESS'
export const CATALOGUE_LIST_FAIL = 'CATALOGUE_LIST_FAIL'

export const CATALOGUE_DETAILS_REQUEST = 'CATALOGUE_DETAILS_REQUEST'
export const CATALOGUE_DETAILS_SUCCESS = 'CATALOGUE_DETAILS_SUCCESS'
export const CATALOGUE_DETAILS_FAIL = 'CATALOGUE_DETAILS_FAIL'

export const CATALOGUE_CREATE_REQUEST = 'CATALOGUE_CREATE_REQUEST'
export const CATALOGUE_CREATE_SUCCESS = 'CATALOGUE_CREATE_SUCCESS'
export const CATALOGUE_CREATE_FAIL = 'CATALOGUE_CREATE_FAIL'
export const CATALOGUE_CREATE_RESET = 'CATALOGUE_CREATE_RESET'

export const CATALOGUE_UPDATE_REQUEST = 'CATALOGUE_UPDATE_REQUEST'
export const CATALOGUE_UPDATE_SUCCESS = 'CATALOGUE_UPDATE_SUCCESS'
export const CATALOGUE_UPDATE_FAIL = 'CATALOGUE_UPDATE_FAIL'
export const CATALOGUE_UPDATE_RESET = 'CATALOGUE_UPDATE_RESET'

export const CATALOGUE_DELETE_REQUEST = 'CATALOGUE_DELETE_REQUEST'
export const CATALOGUE_DELETE_SUCCESS = 'CATALOGUE_DELETE_SUCCESS'
export const CATALOGUE_DELETE_FAIL = 'CATALOGUE_DELETE_FAIL'
